# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug_armeabi-v7a
endif

ifndef verbose
  SILENT = @
endif

CC = gcc
CXX = g++
AR = ar

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

ifeq ($(config),debug_armeabi-v7a)
  PREMAKE4_PLATFORM_NAME = android_armeabi-v7a
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  CC         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-gcc --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  CXX        = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-g++ --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  AR         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-ar
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Debug/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Debug/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -D_DEBUG -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -march=armv7-a -mfloat-abi=softfp -fvisibility=hidden
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -march=armv7-a -mfloat-abi=softfp
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),profile_armeabi-v7a)
  PREMAKE4_PLATFORM_NAME = android_armeabi-v7a
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  CC         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-gcc --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  CXX        = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-g++ --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  AR         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-ar
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Profile/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Profile/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -DNDEBUG -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -O3 -march=armv7-a -mfloat-abi=softfp -fvisibility=hidden
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -march=armv7-a -mfloat-abi=softfp
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release_armeabi-v7a)
  PREMAKE4_PLATFORM_NAME = android_armeabi-v7a
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  CC         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-gcc --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  CXX        = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-g++ --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  AR         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-ar
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Release/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Release/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -DNDEBUG -DAK_OPTIMIZED -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -O3 -march=armv7-a -mfloat-abi=softfp -fvisibility=hidden
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -march=armv7-a -mfloat-abi=softfp
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug_armeabi-v7a-hf)
  PREMAKE4_PLATFORM_NAME = android_armeabi-v7a-hf
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  CC         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-gcc --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  CXX        = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-g++ --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  AR         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-ar
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Debug/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Debug/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -D_DEBUG -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -march=armv7-a -mhard-float -fvisibility=hidden -mhard-float
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -march=armv7-a -mhard-float -Wl,--no-warn-mismatch
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),profile_armeabi-v7a-hf)
  PREMAKE4_PLATFORM_NAME = android_armeabi-v7a-hf
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  CC         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-gcc --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  CXX        = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-g++ --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  AR         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-ar
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Profile/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Profile/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -DNDEBUG -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -O3 -march=armv7-a -mhard-float -fvisibility=hidden -mhard-float
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -march=armv7-a -mhard-float -Wl,--no-warn-mismatch
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release_armeabi-v7a-hf)
  PREMAKE4_PLATFORM_NAME = android_armeabi-v7a-hf
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  CC         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-gcc --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  CXX        = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-g++ --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  AR         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/arm-linux-androideabi-ar
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Release/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Release/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -DNDEBUG -DAK_OPTIMIZED -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -O3 -march=armv7-a -mhard-float -fvisibility=hidden -mhard-float
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -march=armv7-a -mhard-float -Wl,--no-warn-mismatch
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug_x86)
  PREMAKE4_PLATFORM_NAME = android_x86
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  CC         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/i686-linux-android-gcc --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.8/i686-linux-android -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.8
  CXX        = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/i686-linux-android-g++ --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.8/i686-linux-android -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.8
  AR         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/i686-linux-android-ar
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Debug/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Debug/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -D_DEBUG -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -std=c++11 -fvisibility=hidden
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -std=c++11
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),profile_x86)
  PREMAKE4_PLATFORM_NAME = android_x86
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  CC         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/i686-linux-android-gcc --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.8/i686-linux-android -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.8
  CXX        = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/i686-linux-android-g++ --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.8/i686-linux-android -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.8
  AR         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/i686-linux-android-ar
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Profile/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Profile/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -DNDEBUG -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -O3 -std=c++11 -fvisibility=hidden
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -std=c++11
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release_x86)
  PREMAKE4_PLATFORM_NAME = android_x86
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  CC         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/i686-linux-android-gcc --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.8/i686-linux-android -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.8
  CXX        = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/i686-linux-android-g++ --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.8/i686-linux-android -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.8
  AR         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/i686-linux-android-ar
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Release/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Release/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -DNDEBUG -DAK_OPTIMIZED -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -O3 -std=c++11 -fvisibility=hidden
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -std=c++11
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug_arm64-v8a)
  PREMAKE4_PLATFORM_NAME = android_arm64-v8a
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  CC         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/aarch64-linux-android-gcc --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  CXX        = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/aarch64-linux-android-g++ --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  AR         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/aarch64-linux-android-ar
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Debug/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Debug/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -D_DEBUG -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -march=armv8-a -fvisibility=hidden
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -march=armv8-a
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),profile_arm64-v8a)
  PREMAKE4_PLATFORM_NAME = android_arm64-v8a
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  CC         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/aarch64-linux-android-gcc --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  CXX        = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/aarch64-linux-android-g++ --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  AR         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/aarch64-linux-android-ar
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Profile/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Profile/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -DNDEBUG -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -O3 -march=armv8-a -fvisibility=hidden
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -march=armv8-a
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release_arm64-v8a)
  PREMAKE4_PLATFORM_NAME = android_arm64-v8a
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  CC         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/aarch64-linux-android-gcc --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  CXX        = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/aarch64-linux-android-g++ --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot
  AR         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/aarch64-linux-android-ar
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Release/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Release/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -DNDEBUG -DAK_OPTIMIZED -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -O3 -march=armv8-a -fvisibility=hidden
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -march=armv8-a
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug_x86_64)
  PREMAKE4_PLATFORM_NAME = android_x64
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  CC         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/x86_64-linux-android-gcc --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.9/x86_64-linux-android -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.9
  CXX        = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/x86_64-linux-android-g++ --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.9/x86_64-linux-android -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.9
  AR         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/x86_64-linux-android-ar
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Debug/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Debug/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -D_DEBUG -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -std=c++11 -fvisibility=hidden
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -std=c++11
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),profile_x86_64)
  PREMAKE4_PLATFORM_NAME = android_x64
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  CC         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/x86_64-linux-android-gcc --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.9/x86_64-linux-android -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.9
  CXX        = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/x86_64-linux-android-g++ --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.9/x86_64-linux-android -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.9
  AR         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/x86_64-linux-android-ar
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Profile/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Profile/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -DNDEBUG -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -O3 -std=c++11 -fvisibility=hidden
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -std=c++11
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release_x86_64)
  PREMAKE4_PLATFORM_NAME = android_x64
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  CC         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/x86_64-linux-android-gcc --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.9/x86_64-linux-android -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.9
  CXX        = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/x86_64-linux-android-g++ --sysroot=$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/sysroot -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.9/x86_64-linux-android -I$(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/include/c++/4.9
  AR         = $(WWISE_SDK_ROOT)/source/Build/Android/$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/bin/x86_64-linux-android-ar
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Release/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Release/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -DNDEBUG -DAK_OPTIMIZED -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -O3 -std=c++11 -fvisibility=hidden
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -std=c++11
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug)
  PREMAKE4_PLATFORM_NAME = Native
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Debug/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Debug/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -D_DEBUG -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -fvisibility=hidden
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS)
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),profile)
  PREMAKE4_PLATFORM_NAME = Native
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Profile/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Profile/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -DNDEBUG -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -O3 -fvisibility=hidden
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS)
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  PREMAKE4_PLATFORM_NAME = Native
  PREMAKE4_BUILDTARGET_BASENAME = AkStreamMgr
  OBJDIR     = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Release/obj/$(PREMAKE4_BUILDTARGET_BASENAME)
  TARGETDIR  = ../../../$(ANDROID_PLATFORM)_$(ANDROID_ARCH)/Release/lib
  TARGET     = $(TARGETDIR)/libAkStreamMgr.a
  DEFINES   += -DNDEBUG -DAK_OPTIMIZED -DAUDIOKINETIC -DAKSOUNDENGINE_EXPORTS
  INCLUDES  += -I../../../include -I. -I../Common -I../POSIX
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -O3 -fvisibility=hidden
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -Wno-invalid-offsetof -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS)
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/stdafx.o \
	$(OBJDIR)/AkDeviceBase.o \
	$(OBJDIR)/AkDeviceBlocking.o \
	$(OBJDIR)/AkDeviceDeferredLinedUp.o \
	$(OBJDIR)/AkIOMemMgr.o \
	$(OBJDIR)/AkStreamMgr.o \
	$(OBJDIR)/AkTransferDeferred.o \
	$(OBJDIR)/AkIOThread.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking AkStreamMgrAndroid
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning AkStreamMgrAndroid
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -MMD -MP $(DEFINES) $(INCLUDES) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
endif

$(OBJDIR)/stdafx.o: stdafx.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/AkDeviceBase.o: ../Common/AkDeviceBase.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/AkDeviceBlocking.o: ../Common/AkDeviceBlocking.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/AkDeviceDeferredLinedUp.o: ../Common/AkDeviceDeferredLinedUp.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/AkIOMemMgr.o: ../Common/AkIOMemMgr.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/AkStreamMgr.o: ../Common/AkStreamMgr.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/AkTransferDeferred.o: ../Common/AkTransferDeferred.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/AkIOThread.o: ../POSIX/AkIOThread.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif
